linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - wsl
    - gocognit
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 70
issues:
  exclude-rules:
    - text: "G204: Subprocess launched with function call as argument or cmd arguments"
      linters:
        - gosec
